# Generated by Django 5.2.7 on 2025-11-15 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0002_alter_device_name_alter_sensor_hardware_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ts",
                    models.DateTimeField(
                        db_index=True, help_text="زمان ثبت نمونه (timestamp)"
                    ),
                ),
                ("value", models.FloatField(help_text="مقدار اندازه\u200cگیری شده")),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        help_text="داده خام دریافتی از سنسور/پروتکل (در صورت نیاز)",
                        null=True,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("bad", "Bad"),
                            ("suspect", "Suspect"),
                        ],
                        default="good",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="devices.sensor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor Reading",
                "verbose_name_plural": "Sensor Readings",
                "db_table": "sensor_readings",
                "ordering": ["-ts"],
                "indexes": [
                    models.Index(
                        fields=["sensor", "ts"], name="sensor_read_sensor__09bf74_idx"
                    )
                ],
            },
        ),
    ]
