#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Python Package Fixer
Run by double-clicking - no command line required
"""

import os
import sys
import time

def create_logo():
    """Create program logo"""
    logo = """
╔══════════════════════════════════════════════════════════╗
║    🐍 PYTHON PACKAGE FIXER 🛠️                             ║
║    ------------------------------------------------      ║
║    Auto-scan project and create missing __init__.py files║
╚══════════════════════════════════════════════════════════╝
    """
    return logo

def get_current_directory():
    """Get current directory"""
    # If file is executed by double-click
    if hasattr(sys, 'frozen'):
        # Executable mode (pyinstaller)
        return os.path.dirname(sys.executable)
    else:
        # Python script mode
        return os.path.dirname(os.path.abspath(__file__))

def should_ignore_directory(dir_name):
    """Check if directory should be ignored"""
    ignore_dirs = {
        '__pycache__', '.git', '.svn', '.hg',
        '.venv', 'venv', 'env', 'virtualenv',
        '.idea', '.vscode', '.vs', '.history',
        'node_modules', 'dist', 'build',
        '*.egg-info', '.pytest_cache', '.mypy_cache',
        'migrations', 'static', 'media', 'uploads',
        'logs', 'temp', 'tmp', 'cache',
        '.gitlab', '.github', '.circleci',
        'docker', '.docker', 'kubernetes',
        'docs', 'documentation',
    }
    
    ignore_prefixes = ('.', '_')
    
    # Ignore system directories
    if dir_name in ignore_dirs:
        return True
    
    # Ignore directories starting with special characters
    if dir_name.startswith(ignore_prefixes):
        return True
    
    # Ignore directories containing keywords
    ignore_keywords = ['cache', 'temp', 'test', 'backup', 'old', 'bak']
    if any(keyword in dir_name.lower() for keyword in ignore_keywords):
        return True
    
    return False

def is_python_directory(dirpath, filenames):
    """Check if this directory is a Python package"""
    # If __init__.py exists, it's definitely a package
    if '__init__.py' in filenames:
        return True
    
    # If there are Python files other than __init__.py
    python_files = [f for f in filenames if f.endswith('.py') and f != '__init__.py']
    return len(python_files) > 0

def create_init_file(dirpath):
    """Create __init__.py file"""
    init_file_path = os.path.join(dirpath, '__init__.py')
    
    # If file already exists
    if os.path.exists(init_file_path):
        return False, "Already exists"
    
    try:
        # Create file with English content
        content = """\"\"\"
Package: {}

This file was automatically generated by Python Package Fixer.
To make this directory a valid Python package.
\"\"\"

__version__ = "1.0.0"
__author__ = "System"
__description__ = "Auto-generated package"

print(f"Package {__name__} loaded")
""".format(os.path.basename(dirpath))
        
        with open(init_file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return True, "Created"
    except PermissionError:
        return False, "Permission denied"
    except Exception as e:
        return False, f"Error: {str(e)}"

def scan_project(root_dir):
    """Full project scan"""
    print(f"📂 Scanning: {os.path.abspath(root_dir)}")
    print("⏳ Please wait...")
    print("-" * 70)
    
    results = {
        'total_dirs': 0,
        'python_dirs': 0,
        'init_exists': 0,
        'init_created': 0,
        'errors': 0,
        'created_files': []
    }
    
    for dirpath, dirnames, filenames in os.walk(root_dir):
        results['total_dirs'] += 1
        
        # Remove directories that should be ignored
        dirnames[:] = [d for d in dirnames if not should_ignore_directory(d)]
        
        # Check if this directory is Python
        if is_python_directory(dirpath, filenames):
            results['python_dirs'] += 1
            
            # Calculate relative path for better display
            try:
                rel_path = os.path.relpath(dirpath, root_dir)
            except:
                rel_path = dirpath
            
            if rel_path == '.':
                rel_path = 'Root directory'
            
            # Check for __init__.py existence
            if '__init__.py' in filenames:
                results['init_exists'] += 1
                print(f"   ✓ {rel_path}/__init__.py")
            else:
                # Create __init__.py file
                success, message = create_init_file(dirpath)
                
                if success:
                    results['init_created'] += 1
                    results['created_files'].append(rel_path)
                    print(f"   ✅ {rel_path}/__init__.py ({message})")
                else:
                    results['errors'] += 1
                    print(f"   ❌ {rel_path}/__init__.py ({message})")
    
    return results

def show_summary(results):
    """Display scan summary"""
    print("\n" + "=" * 70)
    print("📊 Scan Results Summary:")
    print("=" * 70)
    
    print(f"   📁 Total directories scanned: {results['total_dirs']}")
    print(f"   🐍 Python directories identified: {results['python_dirs']}")
    print(f"   📄 Existing __init__.py files: {results['init_exists']}")
    print(f"   ✨ New __init__.py files created: {results['init_created']}")
    
    if results['errors'] > 0:
        print(f"   ⚠️  Errors: {results['errors']}")
    
    if results['init_created'] > 0:
        print(f"\n📝 Files created:")
        for file_path in results['created_files']:
            print(f"   - {file_path}/__init__.py")
    
    return results

def save_report(results, root_dir):
    """Save report to file"""
    report_path = os.path.join(root_dir, "package_fix_report.txt")
    
    try:
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write("=" * 60 + "\n")
            f.write("Python Package Fix Report\n")
            f.write("=" * 60 + "\n\n")
            f.write(f"Date: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Directory: {os.path.abspath(root_dir)}\n\n")
            
            f.write("Statistics:\n")
            f.write(f"  - Total directories scanned: {results['total_dirs']}\n")
            f.write(f"  - Python directories identified: {results['python_dirs']}\n")
            f.write(f"  - Existing __init__.py files: {results['init_exists']}\n")
            f.write(f"  - New __init__.py files created: {results['init_created']}\n")
            f.write(f"  - Errors: {results['errors']}\n\n")
            
            if results['created_files']:
                f.write("Files created:\n")
                for file_path in results['created_files']:
                    f.write(f"  - {file_path}/__init__.py\n")
        
        return report_path
    except Exception as e:
        return None

def ask_user_choice():
    """Ask user for choice"""
    print("\n" + "=" * 70)
    print("🎯 Select Operation:")
    print("=" * 70)
    print("   1. Scan current directory")
    print("   2. Select different directory")
    print("   3. Exit")
    print("-" * 70)
    
    while True:
        try:
            choice = input("👉 Please enter your choice (1-3): ").strip()
            if choice in ['1', '2', '3']:
                return int(choice)
            print("⚠️  Please enter a valid number (1, 2, or 3)")
        except KeyboardInterrupt:
            print("\n\n👋 Goodbye!")
            sys.exit(0)
        except:
            print("⚠️  Invalid input")

def select_directory():
    """Let user select directory"""
    print("\n📁 Select Directory")
    print("-" * 50)
    
    while True:
        dir_path = input("👉 Enter directory path (or press Enter for current directory): ").strip()
        
        if not dir_path:
            return get_current_directory()
        
        if os.path.isdir(dir_path):
            return os.path.abspath(dir_path)
        else:
            print(f"❌ Directory '{dir_path}' does not exist!")
            retry = input("Try again? (y/n): ").strip().lower()
            if retry != 'y':
                return get_current_directory()

def main():
    """Main function"""
    # Clear screen (if possible)
    os.system('cls' if os.name == 'nt' else 'clear')
    
    # Show logo
    print(create_logo())
    
    # Get user choice
    choice = ask_user_choice()
    
    if choice == 3:
        print("\n👋 Goodbye!")
        return
    
    # Select directory
    if choice == 1:
        target_dir = get_current_directory()
    else:  # choice == 2
        target_dir = select_directory()
    
    print(f"\n🎯 Selected directory: {target_dir}")
    
    # Final confirmation
    confirm = input("Are you sure? (y/n): ").strip().lower()
    if confirm != 'y':
        print("❌ Operation cancelled.")
        return
    
    # Start scanning
    print("\n" + "=" * 70)
    print("🔄 Starting scan...")
    
    results = scan_project(target_dir)
    show_summary(results)
    
    # Save report
    report_path = save_report(results, target_dir)
    if report_path:
        print(f"\n📄 Report saved to: {report_path}")
    
    # Final message
    print("\n" + "=" * 70)
    if results['init_created'] > 0:
        print("🎉 Operation completed successfully!")
        print(f"   {results['init_created']} __init__.py files created.")
    else:
        print("✅ All packages already have __init__.py files.")
    
    # Wait for key press (Windows only)
    if os.name == 'nt':
        print("\n⏎ Press Enter to exit...")
        input()
    else:
        print("\n👋 Done!")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⏹️  Operation stopped by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        print("\n⏎ Press Enter to exit...")
        if os.name == 'nt':
            input()
        sys.exit(1)