FROM python:3.11-slim

# مسیر ثابت برای کل پروژه
WORKDIR /app

# Shared Kernel (DDD)
COPY backend/shared /app/backend/shared

# Python import root
ENV PYTHONPATH=/app

# وابستگی‌های پایه (حداقلی)
RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    pydantic
