# Generated by Django 5.2.7 on 2025-11-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="temperature, humidity, ammonia, rfid, camera, ...",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("unit", models.CharField(help_text="°C, %, ppm, ...", max_length=20)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Sensor Type",
                "verbose_name_plural": "Sensor Types",
                "db_table": "sensor_types",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("edge_controller", "Edge Controller"),
                            ("sensor_node", "Sensor Node"),
                            ("camera", "Camera"),
                            ("gateway", "Gateway"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="نام منطقی دستگاه (edge-01, node-02, ...)",
                        max_length=200,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("fault", "Fault"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="farm.barn",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="farm.farm",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="farm.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "db_table": "devices",
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="نام منطقی سنسور (مثلا Barn1-Temp-01)", max_length=200
                    ),
                ),
                (
                    "hardware_address",
                    models.CharField(
                        blank=True,
                        help_text="آدرس فیزیکی: کانال، پورت، Modbus address، ...",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="devices.device",
                    ),
                ),
                (
                    "sensor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sensors",
                        to="devices.sensortype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor",
                "verbose_name_plural": "Sensors",
                "db_table": "sensors",
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["farm", "barn", "zone"], name="devices_farm_id_05e217_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["type", "status"], name="devices_type_795f6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensor",
            index=models.Index(
                fields=["device", "sensor_type"], name="sensors_device__b44469_idx"
            ),
        ),
    ]
