# Generated by Django 5.2.7 on 2025-11-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(
                help_text="نام منطقی دستگاه (مثلاً edge-01 یا node-02)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="hardware_address",
            field=models.CharField(
                blank=True,
                help_text="آدرس فیزیکی: کانال، پورت، Modbus address و ...",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="name",
            field=models.CharField(
                help_text="نام منطقی سنسور (مثلاً Barn1-Temp-01)", max_length=200
            ),
        ),
    ]
