# Generated by Django 5.2.7 on 2025-11-15 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0002_alter_device_name_alter_sensor_hardware_address_and_more"),
        ("farm", "0002_alter_barn_options_alter_farm_options_and_more"),
        ("livestock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="نام قانون هشدار (مثلاً High Temperature in Barn 1)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="توضیح قانون هشدار", null=True
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("sensor", "Sensor"),
                            ("barn", "Barn"),
                            ("farm", "Farm"),
                            ("animal", "Animal"),
                        ],
                        default="sensor",
                        help_text="دامنه\u200cی قانون (سنسور، سالن، مزرعه، دام)",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warn",
                        max_length=20,
                    ),
                ),
                (
                    "condition_expression",
                    models.CharField(
                        help_text="عبارت شرطی (مثلاً temp > 30 برای 10 دقیقه)",
                        max_length=500,
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        help_text="پارامترهای قانون (thresholds, window, ...)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="این قانون برای کدام مزرعه است؟",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="farm.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Rule",
                "verbose_name_plural": "Alert Rules",
                "db_table": "alert_rules",
                "ordering": ["farm", "severity", "name"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warn",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="پیام هشدار برای نمایش به کاربر"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("ack", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("raised_at", models.DateTimeField(help_text="زمان ایجاد هشدار")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="زمان برطرف شدن هشدار (در صورت وجود)",
                        null=True,
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        help_text="داده\u200cهای کمکی (مقادیر سنسور، context، ...)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="livestock.animal",
                    ),
                ),
                (
                    "barn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="farm.barn",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="farm.farm",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="devices.sensor",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="farm.zone",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        help_text="قانونی که این هشدار را ایجاد کرده (در صورت وجود)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="alerts.alertrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "db_table": "alerts",
                "ordering": ["-raised_at"],
                "indexes": [
                    models.Index(
                        fields=["farm", "severity", "status"],
                        name="alerts_farm_id_2cc86c_idx",
                    ),
                    models.Index(
                        fields=["sensor", "raised_at"], name="alerts_sensor__3bd523_idx"
                    ),
                ],
            },
        ),
    ]
