# Generated by Django 5.2.7 on 2025-11-15 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farm", "0002_alter_barn_options_alter_farm_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RfidTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_code",
                    models.CharField(
                        help_text="کد RFID (UID کارت/گوشی/تگ)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("assigned", "Assigned"),
                            ("lost", "Lost"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="توضیح اختیاری (مثلاً محل فیزیکی تگ زمانی که آزاد است)",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="این تگ در کدام مزرعه ثبت شده است",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfid_tags",
                        to="farm.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFID Tag",
                "verbose_name_plural": "RFID Tags",
                "db_table": "rfid_tags",
                "ordering": ["tag_code"],
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        help_text="گونه (مثلاً cow, sheep, poultry)", max_length=50
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        blank=True,
                        help_text="نژاد (در صورت نیاز)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="کد گوشواره، کد سیستم حسابداری یا هر شناسه\u200cی خارجی",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("alive", "Alive"),
                            ("sold", "Sold"),
                            ("dead", "Dead"),
                            ("missing", "Missing"),
                        ],
                        default="alive",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="توضیحات اضافی (وضعیت سلامتی، سوابق مهم، ...)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animals",
                        to="farm.barn",
                    ),
                ),
                (
                    "current_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animals",
                        to="farm.zone",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to="farm.farm",
                    ),
                ),
                (
                    "rfid_tag",
                    models.OneToOneField(
                        blank=True,
                        help_text="تگ RFID متصل به این دام (در صورت وجود)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animal",
                        to="livestock.rfidtag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animal",
                "verbose_name_plural": "Animals",
                "db_table": "animals",
                "indexes": [
                    models.Index(
                        fields=["farm", "barn", "current_zone"],
                        name="animals_farm_id_c23d15_idx",
                    ),
                    models.Index(
                        fields=["species", "status"], name="animals_species_23c577_idx"
                    ),
                ],
            },
        ),
    ]
