# Generated by Django 5.2.7 on 2025-11-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="barn",
            options={
                "ordering": ["farm", "name"],
                "verbose_name": "Barn",
                "verbose_name_plural": "Barns",
            },
        ),
        migrations.AlterModelOptions(
            name="farm",
            options={
                "ordering": ["name"],
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
            },
        ),
        migrations.AlterModelOptions(
            name="zone",
            options={
                "ordering": ["barn", "name"],
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
            },
        ),
        migrations.AlterField(
            model_name="farm",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="کد داخلی/سازمانی مزرعه (اختیاری)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="آدرس یا توضیح موقعیت مزرعه",
                max_length=500,
                null=True,
            ),
        ),
    ]
